### ISSUE TITLE
Theme background not changing when used with dimmer.

### ISSUE THREAD

**Issue by 4goodapp** [myTerminal/theme-looper#11]
When used with [dimmer.el](https://github.com/gonewest818/dimmer.el) using ivy, the theme backgrounds doesn't change while looping.

_Not sure if this is a theme-looper or dimmer.el issue though._
```
(use-package dimmer
  :config
  (setq dimmer-adjustment-mode :background)
  (setq dimmer-fraction 0.08)
  (add-to-list 'dimmer-exclusion-regexp-list "^\\*helm.*\\|^ \\*Minibuf-.\\|^\\*Ilist\\*$")
  (dimmer-mode t))
```

**Comment by myTerminal** [comment]
I could easily reproduce this issue. I thought using `theme-looper-post-switch-hook` would help, so I tried

    (add-hook 'theme-looper-post-switch-hook
        'dimmer-process-all)

but the above doesn't seem to work for me either.

**Comment by 4goodapp** [comment]
I just try this hook, It work for me when I have only one Emacs window open. Which is fine.
However, When I have two windows open, only the one with active cursor change.

**Comment by myTerminal** [comment]
I'll have to have a deeper dive in `dimmer.el`'s code and will get back to you soon.

**Comment by myTerminal** [comment]
Sorry for not being able to look into this, I guess it'll take me a little longer to get to it.

**Comment by 4goodapp** [comment]
It's fine, not a huge deal I can live with :)

**Comment by myTerminal** [comment]
I'll still keep it open, hoping we find a solution sometime.

**Comment by myTerminal** [comment]
@4goodapp, can we close this one given that we haven't been spending time on it or have come up with a solution yet? We can re-open if needed. What do you think?

**Comment by 4goodapp** [comment]
Yeah, of course.
