### ISSUE TITLE
`theme-looper-select-theme-from-all` gives error on certain themes

### ISSUE THREAD

**Issue by 4goodapp** [myTerminal/theme-looper#12]
Theme package like moe-theme or solarized comes with many variants, example:
Moe-theme can have:
`moe-dark`,  `moe-light-` and `moe` which (I think) default to the dark variant when you load it with  the built-in Emacs command `load-theme`.

Same for solarized, it has `solarized`, `solarized-dark`, `solarized-light`, etc...

Now when you use the command `theme-looper-select-theme-from-all` and you chose the no-variants one (example: just `moe` or `solarized`), it gives this error:
```
Error in post-command-hook (ivy--queue-exhibit): (error "Undefined Custom theme moe")
```
---
`counsel-load-theme` doesn't give this error - It doesn't load it tho.

**Comment by myTerminal** [comment]
I think I noticed it a few before myself but didn't notice the pattern with the theme names you mentioned. This should help find the issue.

**Comment by myTerminal** [comment]
I inspected the code for `counsel-load-theme` and followed a similar pattern in the function `theme-looper-enable-theme`. I found what it does in both the implementations is that whenever a theme is not applied, it silently fails and swallows the error leaving Emacs with no theme, (same as `*default*` which we recently implemented).

I've made the change in [this commit](https://github.com/myTerminal/theme-looper/commit/e074cd3a46ba47093c2bd39e888483daca2b65d7). Kindly try it and let me know if it works.

The other option that I was considering was to omit such themes from the list before presenting it to the user but that would need knowing which ones would fail upfront. What do you think?

**Comment by 4goodapp** [comment]
I just test it, I got any error now, which is fine for me :)

**Comment by 4goodapp** [comment]
Off-topic, 
Are you on [Discord](http://discordapp.com)?

**Comment by myTerminal** [comment]
> Off-topic,
> Are you on [Discord](http://discordapp.com)?

Yes: myTerminal#7613

**Comment by 4goodapp** [comment]
Done, I just send a request.

**Comment by myTerminal** [comment]
> I just test it, I got any error now, which is fine for me :)

Do you think we achieved what we wanted to here? I mean I've seen this error before myself but now that we have it silently handled, I'm not sure what else we can do about those problematic themes.

**Comment by 4goodapp** [comment]
Am fine with the current solution.
