### ISSUE TITLE
Function to re-load theme

### ISSUE THREAD

**Issue by kwstat** [myTerminal/theme-looper#14]
When I am tweaking a theme, I re-load the theme often.  Currently I do that with a keystroke that uses `lambda`:
```
  ("<S-f5>" . (lambda () (interactive)
                (theme-looper-enable-theme (theme-looper--get-current-theme))))
```
Would you be willing to add a proper named function that re-loads the current theme?

I've tried several theme-cycling packages.  Yours is the best.  Thanks.

**Comment by myTerminal** [comment]
Sure, we can create a function with a name like `theme-looper-reload-theme` and that could be useful for other purposes as well.

I'll try to push a version with the new function soon.

By the way, thanks for the compliment!

**Comment by myTerminal** [comment]
Should be taken care of by [this commit](https://github.com/myTerminal/theme-looper/commit/6bc170097f1dfb7ea4db91544c5ab653279e15cd), and an update should be available on MELPA and MELPA-Stable in a few hours.

Thanks for your idea!

**Comment by kwstat** [comment]
works
