### ISSUE TITLE
The first time I try to select a theme, emacs gives an error

### ISSUE THREAD

**Issue by romildo** [myTerminal/theme-looper#15]
I am using `theme-looper` with `emacs 27.1` (with `use-package`) on linux.

The first time I try to load a theme with `theme-looper-select-theme` or `theme-looper-select-theme-from-all` I am getting the error:

```
Error in post-command-hook (ivy--queue-exhibit): (error "Not enough arguments for format string")
```

Subsequent attempts succeeds.

**Comment by myTerminal** [comment]
@romildo, is this still an issue?

**Comment by romildo** [comment]
> @romildo, is this still an issue?

No, it is not. It is working as expected now.

**Comment by myTerminal** [comment]
It appears that one of the changes I made recently might have taken care of this thing internally. Thanks, @romildo!
