### ISSUE TITLE
quote mistakenly escaped in readme example

### ISSUE THREAD

**Issue by protonpopsicle** [myTerminal/theme-looper#2]
I think this line here:

`(global-set-key (kbd "C-\") 'theme-looper-enable-random-theme)`

needs to be:

`(global-set-key (kbd "C-\\") 'theme-looper-enable-random-theme)`

otherwise the second double quotation mark is escaped by the backslash resulting in the string never being closed.

**Comment by myTerminal** [comment]
Thanks, missed it :)
Fixed now.
