### ISSUE TITLE
[enhancement] option to ignore some themes

### ISSUE THREAD

**Issue by zombiefungus** [myTerminal/theme-looper#3]
sometimes you want to cycle throught all themes except maybe one or two (in my case, emacs default themes) and this would be better than listing all installed themes and then removing those.
Or maybe an option to ignore emacs defaults themes?
What do you think?

**Comment by myTerminal** [comment]
That sounds like a valid use-case, let me give it a try.

**Comment by myTerminal** [comment]
Done. Please test :)

**Comment by zombiefungus** [comment]
Like a charm! Thank you so much :) That was FAST
