### ISSUE TITLE
Use regex to define the set of themes

### ISSUE THREAD

**Issue by romildo** [myTerminal/theme-looper#4]
I would like to be able to specify the set of themes and ignored themes using regex. Can this option be added to the package?

**Comment by myTerminal** [comment]
Sure, I'll look at the options. Will get back to you soon!

**Comment by myTerminal** [comment]
At first I did not get the use-case but now I get it: What if you wanted to only select dark themes? Sounds logical.

So, the current implementation starts with all available themes unless you set a list of your favorite ones and removes the list of unfavorite ones from them. That is how the list of desired themes is deduced.

I imagine, setting favorite and unfavorite themes using regular expressions could also be made to work the same way. So, in case you do not specify which ones you'll like, it will start with a collection of all available themes but when you do, it will filter out those using the supplied regular expression. When supplied with a regular expression for the ones to be ignored, those matching will then be removed from the set. This is how I think the behavior can be. I spent some time and already have some working snippets around this approach. What do you think?

**Comment by myTerminal** [comment]
Could not wait, made some changes (including a few breaking ones) :)

Now we have the ability to include and exclude themes using regular expressions.
It would be great if you could have a look and try if it matches our expectations.

As the changes have been pushed to GitHub, a new version should be available on MELPA in a couple of hours. However, I am yet to test my changes (just to be sure), may be include a few more unit-tests and finally publish it to MELPA stable and Marmalade.

**Comment by romildo** [comment]
It is in the right direction. I was thinking in an easy way of selecting a group of themes like the ones provided by doom-themes.

I am going to try the updated version.

**Comment by myTerminal** [comment]
Great! I'll go ahead and finalize the package for version 2.

Can we close the issue now?

**Comment by 4goodapp** [comment]
This package is very handy so, Thank you.

Sometimes, I want to loop through light theme only, and sometimes, through dark one only mostly at night.
Can you implement that please?

**Comment by myTerminal** [comment]
Sounds like a great idea. In fact I've been thinking of having a mechanism where what themes would be applied will depending upon the time of the day. I too have a few ideas in mind.

How about we discuss it in another issue. Would you mind creating a [new issue](https://github.com/myTerminal/theme-looper/issues/new) or should I create one?

**Comment by 4goodapp** [comment]
> How about we discuss it in another issue. Would you mind creating a new issue or should I create one?

Sure! :)

**Comment by 4goodapp** [comment]
Done [here](https://github.com/myTerminal/theme-looper/issues/7).

**Comment by myTerminal** [comment]
Awesome!
