### ISSUE TITLE
Feature request: Add theme-looper-enable-previous-theme option

### ISSUE THREAD

**Issue by 4goodapp** [myTerminal/theme-looper#5]
Useful if you have many themes Installed

**Comment by myTerminal** [comment]
We now have an implementation to move forward as well as backward. Pushed on MELPA, MELPA-Stable & Marmalade. It should be there on the repositories in a couple of hours, except Marmalade, where it's there already.

**Comment by 4goodapp** [comment]
It's working perfectly!
