### ISSUE TITLE
Feature request: Show current theme name and other's in the echo area while looping.

### ISSUE THREAD

**Issue by 4goodapp** [myTerminal/theme-looper#6]
Just like in [iflib](https://github.com/jrosdahl/iflipb/) or [nswbuff](https://github.com/joostkremers/nswbuff/), It would be nice to see theme list while looping through theme.

Something like this:

![image](https://user-images.githubusercontent.com/6249230/54840425-ee7d4980-4cc4-11e9-8edb-ac170fccef7f.png)

**Comment by myTerminal** [comment]
Yes, we can have something like this so that we know at least a few next and previous themes in the list and perform navigation in the list accordingly. This was not the original thought behind the package but can be a good add-on. I plan to work on it this weekend.

**Comment by 4goodapp** [comment]
>  so that we know at least a few next and previous themes in the list and perform navigate the list accordingly

Exactly!!!

> I plan to work on it this weekend.

Perfect! Not urgent though :)

**Comment by myTerminal** [comment]
I've been trying it out and have some working code with me. Currently, my tentative implementation lists the previous two and next two themes alongside the one currently being applied. The list is rendered vertically, thus enlarging the echo area temporarily to hold five lines. I don't see a problem there, do you?

**Comment by 4goodapp** [comment]
Nope it's fine but I'd prefer a horizontal list over a vertical one though.

**Comment by myTerminal** [comment]
I'm thinking the same. I tried with a horizontal list yesterday and there was one thing that bothered me: moving theme names depending upon name lengths. With vertical list, we won't have to worry about different name lengths but I'll guess I'll try to polish the implementation with a horizontal list as it seems more natural.

**Comment by 4goodapp** [comment]
Well then it fine, You can leave it like this :)

**Comment by 4goodapp** [comment]
Maybe you should add an Ivy integration? _Not really necessary though._

**Comment by myTerminal** [comment]
Let's see how it ends up being. I've been trying to find out a way to display the list in the echo area without having those added into the Message buffer. Could not find a way yet, but we will at least have a better user experience with my current progress. I've been busy with other stuff lately, will mostly be pushing an update in two days. Bonus: I am thinking about a few other things now that we are about to have a visual representation of the theme list.

Ivy integration, another good idea. Will need/take more time though :)

**Comment by 4goodapp** [comment]
> I've been busy with other stuff lately, will mostly be pushing an update in two days. 

Take your time, It's already perfect :)

>  Bonus: I am thinking about a few other things now that we are about to have a visual representation of the theme list.

What's the bonus?

> I've been trying to find out a way to display the list in the echo area without having those added into the Message buffer. 

On the sreenshot above, it's the package [nswbuff](https://github.com/joostkremers/nswbuff/). [iflipb](https://github.com/jrosdahl/iflipb/) have similar output too, so maybe having a look at there implementation will give you an idea.

**Comment by myTerminal** [comment]
> What's the bonus?

I was thinking of a semi-interactive interface for selecting themes, but that is just too much for now, may be later :)

> On the sreenshot above, it's the package nswbuff. iflipb have similar output too, so maybe having a look at there implementation will give you an idea.

I'll have a look.

**Comment by 4goodapp** [comment]
> I was thinking of a semi-interactive interface for selecting themes, 

What do you mean by _ semi-interactive_? Am not sure I understand.

**Comment by myTerminal** [comment]
> What do you mean by _ semi-interactive_? Am not sure I understand.

Maybe an interface that you can start and then do much more than just looping through themes, maybe filtering them, searching by categories, etc. Just a thought for now, we'll see where it goes.

By the way, just pushed some changes, could you try it out and provide your feedback?

**Comment by 4goodapp** [comment]
> By the way, just pushed some changes, could you try it out and provide your feedback?

Sure! :)

**Comment by 4goodapp** [comment]
It' work perfectly!

![image](https://user-images.githubusercontent.com/6249230/55284472-f85b1880-5366-11e9-821f-29f41d3394be.png)

**Comment by 4goodapp** [comment]
> Maybe an interface that you can start and then do much more than just looping through themes, maybe filtering them, searching by categories, etc. Just a thought for now, we'll see where it goes.

Well why not. Personally, am already happy with what we have currently have :)

**Comment by myTerminal** [comment]
Cool, glad to know that. This one being my first Emacs package that I created, I did not have all these ideas back then. Personally I'm happy to see the improvements as well, and am so excited to see more.

So, should we close this one and take care of other items like ivy integration in future?

**Comment by 4goodapp** [comment]
> So, should we close this one and take care of other items like ivy integration in future?

Cool, that's a great idea. :)
