### ISSUE TITLE
Feature request: loop through theme category: light - dark - all

### ISSUE THREAD

**Issue by 4goodapp** [myTerminal/theme-looper#7]
There Is one catch on this though when you use dark theme like [challenger-deep-theme](https://peach-melpa.org/themes/challenger-deep-theme) as there is no "light" or "dark"  in the theme name. So using regex, we may miss them.

**Comment by myTerminal** [comment]
Correct. Not every dark theme is named that way. We'll have to take care of it some other way.

I guess if there's not a lot of themes to be considered, may be you can create a map of themes marking them as 'dark' or 'light' and/or specify which ones you would be interested in during a particular part of the day?

**Comment by 4goodapp** [comment]
Well maybe something like: `theme-looper-set-favorite-dark-themes` and `theme-looper-set-favorite-light-themes` where we can put our favorites dark and light theme.
then a command to call them independently:

Like: 
```(use-package theme-looper
:bind
("M-s-t" . `theme-looper-set-favorite-dark-themes`)
("M-s-r" . `theme-looper-set-favorite-light-themes`)
;; ...
:config
  (theme-looper-set-favorite-dark-themes '(zerodark darktooth challenger-deep  flucui-dark moe-dark sanityinc-tomorrow-blue kaolin-mono-dark spacemacs-dark dracula gruvbox-dark-hard))

  (theme-looper-set-favorite-light-themes '(moe-light  kaolin-mono-light spacemacs-light))
)
```

Hope you got the idea :)

**Comment by myTerminal** [comment]
Sounds reasonable but I'm just afraid it might pollute the library to have three functions to set favorite themes, three functions to move to the next theme, etc. The thing I'm concerned about is that we shouldn't complicate the API for new users or ones who are not concerned about this particular feature. I guess we'll have to give it some (more) thought and handle it a bit more systematically.

**Comment by 4goodapp** [comment]
> Sounds reasonable but I'm just afraid it might pollute the library to have three functions to set favorite themes, three functions to move to the next theme, etc.

That's true, I was thinking about the same too.
So may be just leave it like it is currently and add a `theme-looper-enable-previous-theme` function will  works for me (personally).

And who knows, maybe make another package, theme-looper+ with extra functionality?

The lack of  `theme-looper-enable-previous-theme` function is the only thing that is bothering me. :)

**Comment by myTerminal** [comment]
Yes, I'll keep this on the back-burner for now as I have a few other stuff waiting. Will get back to it as I get a chance. An entirely different package? Great idea!

**Comment by 4goodapp** [comment]
Cool :)

**Comment by romildo** [comment]
Wouldn't an entirely different new package duplicate code and efforts to maintain both?

**Comment by myTerminal** [comment]
I have a plan: we can make this one as a dependency and use code from here in the new one. Thoughts?

**Comment by 4goodapp** [comment]
Am fine with whatever you guys decide, Now I arranger light theme first in my list of favorite themes and the dark ones last in the list and with the new "previous" switch,I can easily switch to whatever color. 
Didn't have this idea when request this feature.

**Comment by 4goodapp** [comment]
Many theme don't have the /light$/ or /dark$/ label. So I think this is a good idea after all.

> ... we can make this one as a dependency and use code from here in the new one. Thoughts?

I think this is a good idea though. So we can put "fancier" features like Ivy/Counsel integration on it on it. 
Thoughts?

**Comment by myTerminal** [comment]
Agreed.
